openapi: 3.0.2
info:
  title: Veresk API
  version: 0.1.0
  description: Fractal showcase app
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: /
paths:
  "/fractals/{fractal_id}":
    summary: Update fractal
    delete:
      operationId: app.fractals.fractals_delete
      parameters:
        - name: fractal_id
          in: path
          description: ID of fractal to delete
          required: true
          schema:
            type: string
            example: "321832891ds"
      responses:
        "204":
          description: Fractal deleted
    patch:
      operationId: app.fractals.fractals_update
      parameters:
        - name: fractal_id
          in: path
          description: ID of fractal to update
          required: true
          schema:
            type: string
            example: "deadbeef"
      requestBody:
        description: Update existing fractal
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/fractal"
      responses:
        "204":
          description: Fractal updated
  /fractals:
    summary: Manage fractals
    get:
      operationId: app.fractals.fractals_list
      responses:
        "200":
          description: List all available fractals
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/fractal"
    post:
      operationId: app.fractals.fractals_add
      requestBody:
        description: Add new fractal
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/fractal"
      responses:
        "204":
          description: Fractal added
  /status:
    summary: Return health information
    get:
      operationId: app.health.status
      responses:
        "200":
          description: Health summary information
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
                    example: "OK"
components:
  schemas:
    fractal:
      type: object
      properties:
        complex_real:
          type: number
          example: -0.42
        complex_imaginary:
          type: number
          example: 0.6
